# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0004_auto_20170325_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
