# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_auto_20170325_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentfrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentwriter', to='Twitter.useradd'),
        ),
    ]
