# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0007_auto_20170326_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentfrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentw', to='Twitter.useradd'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweetfrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Twitter.useradd'),
        ),
    ]
