# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=2500)),
                ('posted_by', models.CharField(max_length=2500)),
                ('type_choice', models.CharField(max_length=2500)),
                ('type', models.CharField(max_length=2500)),
                ('content', models.CharField(max_length=250000)),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
